package br.smartbusiness.metadado.conversor.enums;

public enum TipoConversaoXsl {

	CONVERTER_INSTANCIA_USANDO_TEMPLATENAME, 
	CONVERTER_INSTANCIA_FILE_USANDO_TEMPLATENAME, 
	CONVERTER_INSTANCIA_FILE_USANDO_TEMPLATENAME_FILE,
	CONVERTER_INSTANCIA_STRINBUFFER_USANDO_TEMPLATENAME_STRING_BUFFER;
}
